// SPOTIFY USER
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

// LIST PLAYLISTS
export const LIST_PLAYLISTS_REQUEST = 'LIST_PLAYLISTS_REQUEST';
export const LIST_PLAYLISTS_SUCCESS = 'LIST_PLAYLISTS_SUCCESS';
export const LIST_PLAYLISTS_FAILURE = 'LIST_PLAYLISTS_FAILURE';

export const FETCH_PLAYLIST_DETAIL_REQUEST = 'FETCH_PLAYLIST_DETAIL_REQUEST';
export const FETCH_PLAYLIST_DETAIL_SUCCESS = 'FETCH_PLAYLIST_DETAIL_SUCCESS';
export const FETCH_PLAYLIST_DETAIL_FAILURE = 'FETCH_PLAYLIST_DETAIL_FAILURE';

export const FETCH_PLAYLIST_TRACKS_REQUEST = 'FETCH_PLAYLIST_TRACKS_REQUEST';
export const FETCH_PLAYLIST_TRACKS_SUCCESS = 'FETCH_PLAYLIST_TRACKS_SUCCESS';
export const FETCH_PLAYLIST_TRACKS_FAILURE = 'FETCH_PLAYLIST_TRACKS_FAILURE';

// CREATE PLAYLIST
export const SEARCH_ARTISTS_REQUEST = 'SEARCH_ARTISTS_REQUEST';
export const SEARCH_ARTISTS_SUCCESS = 'SEARCH_ARTISTS_SUCCESS';
export const SEARCH_ARTISTS_FAILURE = 'SEARCH_ARTISTS_FAILURE';

export const REMOVE_TRACKS_REQUEST = 'REMOVE_TRACKS_REQUEST';
export const REMOVE_TRACKS_SUCCESS = 'REMOVE_TRACKS_SUCCESS';
export const REMOVE_TRACKS_FAILURE = 'REMOVE_TRACKS_FAILURE';

// OLD ACTIONS

export const ADD_ARTIST_REQUEST = 'ADD_ARTIST_REQUEST';
export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_FAILURE = 'ADD_ARTIST_FAILURE';

export const REMOVE_ARTIST = 'REMOVE_ARTIST';

export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAILURE = 'CREATE_PLAYLIST_FAILURE';

export const GET_ARTIST_TOP_TRACKS_REQUEST = 'GET_ARTIST_TOP_TRACKS_REQUEST';
export const GET_ARTIST_TOP_TRACKS_SUCCESS = 'GET_ARTIST_TOP_TRACKS_SUCCESS';
export const GET_ARTIST_TOP_TRACKS_FAILURE = 'GET_ARTIST_TOP_TRACKS_FAILURE';

export const ADD_TRACKS_PLAYLIST_REQUEST = 'ADD_TRACKS_PLAYLIST_REQUEST';
export const ADD_TRACKS_PLAYLIST_SUCCESS = 'ADD_TRACKS_PLAYLIST_SUCCESS';
export const ADD_TRACKS_PLAYLIST_FAILURE = 'ADD_TRACKS_PLAYLIST_FAILURE';
