export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const ADD_ARTIST_REQUEST = 'ADD_ARTIST_REQUEST';
export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_FAILURE = 'ADD_ARTIST_FAILURE';

export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAILURE = 'CREATE_PLAYLIST_FAILURE';

export const GET_ARTIST_TOP_TRACKS_REQUEST = 'GET_ARTIST_TOP_TRACKS_REQUEST';
export const GET_ARTIST_TOP_TRACKS_SUCCESS = 'GET_ARTIST_TOP_TRACKS_SUCCESS';
export const GET_ARTIST_TOP_TRACKS_FAILURE = 'GET_ARTIST_TOP_TRACKS_FAILURE';

export const ADD_TRACKS_PLAYLIST_REQUEST = 'ADD_TRACKS_PLAYLIST_REQUEST';
export const ADD_TRACKS_PLAYLIST_SUCCESS = 'ADD_TRACKS_PLAYLIST_SUCCESS';
export const ADD_TRACKS_PLAYLIST_FAILURE = 'ADD_TRACKS_PLAYLIST_FAILURE';
