version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: "circleci/node:10.9"
  branches:
    only:
      - master
      - develop

jobs:
  build:
    <<: *defaults

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  prettier:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: './node_modules/.bin/prettier --single-quote --write "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}"'

  tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      # run tests!
      - run: yarn test
