version: 2.1

restore-workspace: &restore-workspace
  attach_workspace:
    at: ~/

branch-filter: &branch-filter
  branches:
    only: [master]

executors:
  node:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/playlish

jobs:
  checkout-install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: playlish-node-modules-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: playlish-node-modules-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: ~/
          paths: playlish

  test:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn test

  yarn-build:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths: playlish/build

  # deploy:
  #   executor: node
  #   parameters:
  #     {
  #       distributor: { type: string },
  #       bucket: { type: string },
  #       cloudfront_id: { type: string },
  #     }
  #   steps:
  #     - *restore-workspace
  #     - run: bash .circleci/scripts/s3-sync.sh << parameters.bucket >> << parameters.cloudfront_id >> << parameters.distributor >>
  #     run: bash echo ""

workflows:
  version: 2

  build-deploy:
    jobs:
      - checkout-install-dependencies
      - test:
          requires: [checkout-install-dependencies]
      - yarn-build:
          name: build
          requires: [checkout-install-dependencies]
